In [35]:
import pandas as pd
import numpy as np
from smart.model import RFModelBalle
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [36]:
df = pd.read_csv('dataset/datasetTrajectoire.csv')
df

,col1_1,col1_2,col2_1,col2_2,col3_1,col3_2,col4_1,col4_2,col5_1,col5_2,...,col41_2,col42_1,col42_2,col43_1,col43_2,col44_1,col44_2,col45_1,col45_2,label
0,231.0,304.0,250.0,287.0,266.0,287.0,252.0,283.0,275.0,284.0,...,73.0,495.0,56.0,490.0,68.0,516.0,78.0,503.0,62.0,2.0
1,230.0,304.0,239.0,303.0,242.0,297.0,263.0,263.0,281.0,273.0,...,74.0,490.0,80.0,502.0,73.0,503.0,64.0,499.0,57.0,2.0
2,227.0,306.0,248.0,282.0,247.0,296.0,271.0,278.0,255.0,268.0,...,80.0,502.0,61.0,513.0,66.0,493.0,57.0,522.0,51.0,2.0
3,236.0,304.0,250.0,280.0,239.0,273.0,251.0,287.0,261.0,261.0,...,78.0,483.0,78.0,501.0,76.0,509.0,63.0,500.0,63.0,2.0
4,248.0,286.0,251.0,294.0,265.0,296.0,260.0,266.0,269.0,283.0,...,82.0,484.0,77.0,496.0,73.0,491.0,65.0,512.0,56.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3563,393.0,80.0,408.0,76.0,392.0,70.0,391.0,77.0,411.0,70.0,...,248.0,373.0,236.0,384.0,236.0,356.0,243.0,376.0,226.0,12.0
3564,413.0,97.0,408.0,83.0,391.0,90.0,395.0,74.0,385.0,69.0,...,244.0,370.0,222.0,375.0,232.0,365.0,241.0,351.0,218.0,12.0
3565,399.0,79.0,401.0,84.0,394.0,84.0,388.0,82.0,387.0,71.0,...,253.0,371.0,240.0,375.0,239.0,357.0,233.0,362.0,246.0,12.0
3566,395.0,106.0,390.0,85.0,387.0,70.0,392.0,78.0,407.0,84.0,...,245.0,360.0,245.0,365.0,224.0,375.0,238.0,353.0,229.0,12.0
3567,399.0,94.0,399.0,88.0,399.0,82.0,399.0,76.0,399.0,70.0,...,241.0,375.0,232.0,371.0,229.0,368.0,229.0,362.0,232.0,12.0

In [37]:
X = df.drop(['label'], axis=1).values
y = df['label'].values
y.shape

(3568,)

In [38]:
np.unique(y)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [39]:
# Load the data
model = RFModelBalle.construct_model(max_depth = 8, n_estimators = 20)

In [40]:
# Normalize the data
scaler = StandardScaler()
encoder = LabelEncoder()

In [41]:
X = scaler.fit_transform(X)
y = encoder.fit_transform(y)
y

array([ 1,  1,  1, ..., 11, 11, 11], dtype=int64)

In [42]:
output_y = np.unique(y)
output_y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [43]:
# Split the data
X_train, X_test, y_train, y_test = model.train_test_split(X, y, test_size=0.2, random_state=42)

In [44]:
# Train the model
model.fit(X_train, y_train)

In [45]:
# Evaluate the model
model.evaluate(X_test, y_test)

0.9957983193277311

# Test

In [46]:
test_df = pd.read_csv('dataset/datasetTest.csv')
test_df

,col1_1,col1_2,col2_1,col2_2,col3_1,col3_2,col4_1,col4_2,col5_1,col5_2,...,col41_2,col42_1,col42_2,col43_1,col43_2,col44_1,col44_2,col45_1,col45_2,label
0,346.5,281.5,342.0,276.5,335.0,285.0,321.5,285.0,288.5,45.0,...,74.0,252.0,64.0,253.0,46.0,247.0,45.0,240.5,43.0,6.0
1,337.5,277.5,342.0,267.5,344.0,267.0,323.5,273.0,280.5,53.0,...,83.0,243.0,63.0,244.0,32.0,243.0,55.0,248.5,29.0,6.0
2,329.5,284.5,331.0,284.5,344.0,278.0,315.5,282.0,292.5,40.0,...,77.0,237.0,59.0,248.0,39.0,255.0,43.0,252.5,33.0,6.0
3,330.5,268.5,338.0,276.5,327.0,278.0,316.5,277.0,284.5,56.0,...,83.0,243.0,61.0,256.0,27.0,256.0,39.0,256.5,40.0,6.0
4,341.5,271.5,337.0,275.5,329.0,274.0,328.5,279.0,281.5,58.0,...,76.0,249.0,66.0,242.0,33.0,247.0,55.0,247.5,44.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,253.0,270.0,260.0,273.0,243.0,286.0,255.0,278.0,250.0,289.0,...,73.0,346.0,66.0,344.0,71.0,332.0,67.0,341.0,56.0,10.0
701,246.0,270.0,243.0,274.0,257.0,284.0,247.0,289.0,252.0,289.0,...,73.0,340.0,63.0,330.0,70.0,328.0,69.0,337.0,73.0,10.0
702,242.0,283.0,243.0,282.0,254.0,289.0,249.0,287.0,255.0,277.0,...,56.0,342.0,62.0,331.0,69.0,342.0,66.0,339.0,65.0,10.0
703,248.0,285.0,256.0,280.0,246.0,278.0,261.0,275.0,242.0,284.0,...,65.0,331.0,67.0,338.0,60.0,344.0,67.0,335.0,68.0,10.0
704,260.0,275.0,242.0,281.0,252.0,282.0,259.0,284.0,257.0,281.0,...,58.0,343.0,74.0,344.0,70.0,346.0,62.0,334.0,74.0,10.0

In [47]:
X_test_fin = test_df.drop(['label'], axis=1).values
y_test_fin = test_df['label'].values
y_test_fin.shape

(705,)

In [48]:
output_y_test_fin = np.unique(y_test_fin)
output_y_test_fin

array([ 1.,  2.,  6.,  9., 10.])

In [49]:
new_scaler = StandardScaler()

In [50]:
X_test_fin = new_scaler.fit_transform(X_test_fin)
y_test_fin = encoder.transform(y_test_fin)
np.unique(y_test_fin)

array([0, 1, 5, 8, 9], dtype=int64)

In [ ]:
# Step 4: Evaluate the model
score = model.evaluate(X_test_fin, y_test_fin)
score