In [52]:
import pandas as pd
import numpy as np
from smart.model import RFModelBalle
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report

In [53]:
df = pd.read_csv('dataset/datasetTrajectoire - Copy.csv')
df

,col1_1,col1_2,col2_1,col2_2,col3_1,col3_2,col4_1,col4_2,col5_1,col5_2,...,col41_2,col42_1,col42_2,col43_1,col43_2,col44_1,col44_2,col45_1,col45_2,label
0,210,316,217,285,232,281,230,295,246,264,...,133,497,103,519,110,514,96,526,67,1
1,211,292,239,305,222,290,228,273,247,276,...,110,486,110,520,111,528,80,510,80,1
2,213,318,235,300,247,307,239,294,242,279,...,112,514,109,524,84,502,84,526,86,1
3,213,316,215,304,225,286,229,293,248,283,...,127,501,106,505,105,513,93,534,86,1
4,213,318,242,301,226,304,237,302,239,280,...,110,499,102,516,95,525,74,535,90,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3563,558,295,551,307,531,304,544,272,524,256,...,59,414,58,415,47,426,30,416,39,12
3564,558,307,552,305,554,306,544,286,539,259,...,74,410,40,414,46,421,43,416,31,12
3565,558,310,542,289,530,290,532,282,520,279,...,74,418,55,418,47,417,43,405,29,12
3566,559,317,529,312,536,290,527,283,535,259,...,60,423,47,412,33,412,54,408,38,12
3567,559,316,558,307,538,280,545,288,544,276,...,62,417,45,423,33,404,28,422,28,12

In [54]:
X = df.drop(['label'], axis=1).values
y = df['label'].values
y.shape

(3568,)

In [55]:
# Avant encoder y
np.unique(y)

array([ 1,  3,  4,  6,  7,  8, 10, 11, 12], dtype=int64)

In [56]:
# Load the data
model = RFModelBalle.construct_model(max_depth = 8, n_estimators = 20)

In [57]:
# Normalize the data
scaler = StandardScaler()
encoder = LabelEncoder()

In [58]:
X = scaler.fit_transform(X)
y = encoder.fit_transform(y)
y

array([0, 0, 0, ..., 8, 8, 8], dtype=int64)

In [59]:
output_y = np.unique(y)
output_y

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [60]:
# Split the data
X_train, X_test, y_train, y_test = model.train_test_split(X, y, test_size=0.2, random_state=42)

In [61]:
# Train the model
model.fit(X_train, y_train)

In [62]:
# Evaluate the model
model.evaluate(X_test, y_test)

1.0

# Test

In [73]:
test_df = pd.read_csv('dataset/datasetTest - Copy.csv')
test_df

,col1_1,col1_2,col2_1,col2_2,col3_1,col3_2,col4_1,col4_2,col5_1,col5_2,...,col41_2,col42_1,col42_2,col43_1,col43_2,col44_1,col44_2,col45_1,col45_2,label
0,238.5,31.5,244.5,39.5,227.5,38.5,246.5,42.5,238.5,46.0,...,69.0,384.5,78.0,372.5,69.0,379.5,66.0,373.5,76.0,1
1,237.5,36.5,232.5,31.5,239.5,34.5,236.5,28.5,227.5,32.0,...,62.0,375.5,77.0,376.5,69.0,375.5,75.0,373.5,73.0,1
2,239.5,39.5,238.5,39.5,246.5,24.5,245.5,34.5,236.5,33.0,...,75.0,366.5,67.0,383.5,72.0,366.5,77.0,372.5,76.0,1
3,238.5,33.5,237.5,30.5,240.5,41.5,232.5,40.5,222.5,43.0,...,74.0,381.5,78.0,373.5,60.0,366.5,61.0,369.5,73.0,1
4,228.5,41.5,235.5,26.5,239.5,38.5,242.5,39.5,223.5,43.0,...,77.0,367.5,66.0,382.5,63.0,369.5,60.0,376.5,78.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,253.0,270.0,260.0,273.0,243.0,286.0,255.0,278.0,250.0,289.0,...,73.0,346.0,66.0,344.0,71.0,332.0,67.0,341.0,56.0,10
701,246.0,270.0,243.0,274.0,257.0,284.0,247.0,289.0,252.0,289.0,...,73.0,340.0,63.0,330.0,70.0,328.0,69.0,337.0,73.0,10
702,242.0,283.0,243.0,282.0,254.0,289.0,249.0,287.0,255.0,277.0,...,56.0,342.0,62.0,331.0,69.0,342.0,66.0,339.0,65.0,10
703,248.0,285.0,256.0,280.0,246.0,278.0,261.0,275.0,242.0,284.0,...,65.0,331.0,67.0,338.0,60.0,344.0,67.0,335.0,68.0,10
704,260.0,275.0,242.0,281.0,252.0,282.0,259.0,284.0,257.0,281.0,...,58.0,343.0,74.0,344.0,70.0,346.0,62.0,334.0,74.0,10

In [74]:
X_test_fin = test_df.drop(['label'], axis=1).values
y_test_fin = test_df['label'].values
y_test_fin.shape

(705,)

In [75]:
# Avant encoder y_test_fin
np.unique(y_test_fin)

array([ 1,  6, 10], dtype=int64)

In [76]:
new_scaler = StandardScaler()

In [77]:
X_test_fin = new_scaler.fit_transform(X_test_fin)
y_test_fin = encoder.transform(y_test_fin)
y_test_fin

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6], dtype=int64)

In [78]:
# Apres encoder y_test_fin
output_y_test_fin = np.unique(y_test_fin)
output_y_test_fin

array([0, 3, 6], dtype=int64)

In [79]:
# Step 4: Evaluate the model
score = model.evaluate(X_test_fin, y_test_fin)
score

0.2297872340425532

In [80]:
# Step 5: Predict
y_pred = model.predict(X_test_fin)
y_pred, y_test_fin

(array([7, 6, 6, 6, 7, 6, 6, 6, 6, 0, 0, 7, 7, 6, 6, 6, 6, 0, 0, 6, 6, 6,
        6, 6, 6, 7, 6, 0, 7, 0, 0, 7, 0, 0, 6, 6, 6, 7, 6, 0, 6, 6, 6, 6,
        7, 6, 0, 6, 6, 6, 6, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 5, 5, 2, 2, 5, 5, 5, 5, 5, 2, 5, 5, 5, 2, 5, 2, 5,
        2, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 6, 6, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1, 6,
        1, 1, 6, 6, 6, 6, 6, 6, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 2, 7, 7, 7, 2, 7, 2, 7, 7, 7, 7, 7, 7,
        7, 2, 7, 2, 7, 7, 7, 2, 6, 6, 6, 6, 6, 1, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 1, 6, 6, 6, 1, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3,
        1, 3, 3, 4, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 8, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 5, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 6, 0, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 7, 1, 6, 1, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 3,
        3, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 5, 8, 8, 8, 8,
        8, 5, 8, 8, 8, 8, 8, 8, 5, 8, 8, 8, 8, 8, 8, 1, 1, 1, 8, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 6, 7, 7, 7, 6, 7, 6, 7, 6, 6, 7, 6, 7, 7, 6, 6, 6, 6, 6, 6,
        7], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6], dtype=int64))

In [81]:
# Confusion matrix
confusion_matrix(y_test_fin, y_pred)

array([[ 74,  17,  54,  13,   1,  15, 113,  25,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  2,   4,  96,   3,   0,  20,  17,   1,   1],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 19,  22,  51,   0,   0,   3,  85,  29,  40],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0]], dtype=int64)

In [83]:
print(classification_report(y_test_fin, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.24      0.36       312
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.19      0.02      0.04       144
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         0
           6       0.40      0.34      0.37       249
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0

    accuracy                           0.23       705
   macro avg       0.15      0.07      0.09       705
weighted avg       0.52      0.23      0.30       705

c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\bbbbb\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))